sudo: false

language: node_js

node_js:
  - "8.11.1"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5


before_install:
  - if [[ $(uname -s) == 'Linux' ]]; then
       export CXX="clang++-3.5";
       export CC="clang-3.5";
    fi;
  - npm install -g npm@5.6.0


install:
  - cd examples/addon && npm i --clang=1
  - cd ../deps && npm i --clang=1
  - cd ../.. && npm i --clang=1
  - cd test && npm i --clang=1
  - cd ..


script:
  - cd examples/addon && node .
  - cd ../deps && node .
  - cd ../.. && node .
  - cd test && npm test
  - cd ..
