dist: trusty
sudo: false

language: node_js

node_js:
  - "8.11.4"


before_install:
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.0


install:
  - cd test
  - npm i
  - cd ..


script:
  - cd test
  - npm test
  - cd ..
