language: node_js

node_js:
  - "12.13.0"


matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "MacOS"
    os: osx
  - name: "Windows"
    os: windows

install:
  - cd test
  - npm ci
  - cd ..

script:
  - cd test
  - npm test
  - ./build/Release/test
